version: '3'
services:
  ambweb:
    build: ./ambweb
    command: /code/manage.py runserver
    ports:
      - "${AMBWEB_PORT:-8000}:8000"
    depends_on:
      - db
    volumes:
      - ./ambweb:/code
  amb_client:
    build: ./ambp3client
    command: python /code/amb_client.py -f /code/${AMB_LOCAL_CONF:-local_conf.yaml}
    depends_on:
      - db
    volumes:
      - ./ambp3client:/code
  amb_laps:
    build: ./ambp3client
    command: python /code/amb_laps.py -f /code/${AMB_LOCAL_CONF:-local_conf.yaml}
    depends_on:
      - db
    volumes:
      - ./ambp3client:/code
  db:
    image: "mariadb:10.4"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-test}'
    volumes:
      - ./mysql-datadir:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
